FROM alpine:latest
LABEL maintainer="lemi"

# 패키지 업데이트 및 필요한 소프트웨어 설치
RUN apk --no-cache update && \
    apk --no-cache add apache2 php82 php82-apache2 php82-mysqli php82-json php82-session mysql mysql-client supervisor && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /run/apache2 /run/mysqld /var/lib/mysql

# MySQL 초기 설정 및 데이터 디렉토리 설정
RUN mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

# MySQL 및 Apache 설정 파일 복사
COPY docker-kknockfile/my.cnf /etc/mysql/my.cnf
COPY docker-kknockfile/supervisord.conf /etc/supervisord.conf

# 웹 애플리케이션 파일 복사
WORKDIR /var/www/localhost/htdocs
COPY docker-kknockfile/ .

# 포트 80 열기
EXPOSE 80

# Supervisor를 사용하여 Apache와 MySQL을 함께 실행
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

